const Dots = ({
  width = 110,
  height = 162,
  color = '#212121',
  style,
  onClick,
  className,
}: {
  color?: string;
  width?: number;
  height?: number;
  style?: React.CSSProperties;
  onClick?: () => void;
  className?: string;
}) => {
  return (
    <div onClick={onClick} className={className} style={style}>
      <svg
        width={width ?? '100%'}
        height={height ?? '100%'}
        viewBox="0 0 110 162"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        className="dots-svg"
      >
        <rect width="6" height="6" rx="2" fill={color} />
        <rect x="26" width="6" height="6" rx="2" fill={color} />
        <rect x="52" width="6" height="6" rx="2" fill={color} />
        <rect x="78" width="6" height="6" rx="2" fill={color} />
        <rect x="104" width="6" height="6" rx="2" fill={color} />
        <rect y="26" width="6" height="6" rx="2" fill={color} />
        <rect
          x="26"
          y="26"
          width="6"
          height="6"
          rx="2"
          fill="var(--main-color-bold)"
        />
        <rect
          x="52"
          y="26"
          width="6"
          height="6"
          rx="2"
          fill="var(--main-color-bold)"
        />
        <rect
          x="78"
          y="26"
          width="6"
          height="6"
          rx="2"
          fill="var(--main-color-bold)"
        />
        <rect
          x="104"
          y="26"
          width="6"
          height="6"
          rx="2"
          fill="var(--main-color-bold)"
        />
        <rect
          y="52"
          width="6"
          height="6"
          rx="2"
          fill="var(--main-color-bold)"
        />
        <rect
          x="26"
          y="52"
          width="6"
          height="6"
          rx="2"
          fill="var(--main-color-bold)"
        />
        <rect
          x="52"
          y="52"
          width="6"
          height="6"
          rx="2"
          fill="var(--main-color-bold)"
        />
        <rect
          x="78"
          y="52"
          width="6"
          height="6"
          rx="2"
          fill="var(--main-color-bold)"
        />
        <rect
          x="104"
          y="52"
          width="6"
          height="6"
          rx="2"
          fill="var(--main-color-bold)"
        />
        <rect
          y="78"
          width="6"
          height="6"
          rx="2"
          fill="var(--main-color-bold)"
        />
        <rect
          x="26"
          y="78"
          width="6"
          height="6"
          rx="2"
          fill="var(--main-color-bold)"
        />
        <rect
          x="52"
          y="78"
          width="6"
          height="6"
          rx="2"
          fill="var(--main-color-bold)"
        />
        <rect
          x="78"
          y="78"
          width="6"
          height="6"
          rx="2"
          fill="var(--main-color-bold)"
        />
        <rect
          x="104"
          y="78"
          width="6"
          height="6"
          rx="2"
          fill="var(--main-color-bold)"
        />
        <rect
          y="104"
          width="6"
          height="6"
          rx="2"
          fill="var(--main-color-bold)"
        />
        <rect
          x="26"
          y="104"
          width="6"
          height="6"
          rx="2"
          fill="var(--main-color-bold)"
        />
        <rect
          x="52"
          y="104"
          width="6"
          height="6"
          rx="2"
          fill="var(--main-color-bold)"
        />
        <rect
          x="78"
          y="104"
          width="6"
          height="6"
          rx="2"
          fill="var(--main-color-bold)"
        />
        <rect
          x="104"
          y="104"
          width="6"
          height="6"
          rx="2"
          fill="var(--main-color-bold)"
        />
        <rect
          y="130"
          width="6"
          height="6"
          rx="2"
          fill="var(--main-color-bold)"
        />
        <rect
          x="26"
          y="130"
          width="6"
          height="6"
          rx="2"
          fill="var(--main-color-bold)"
        />
        <rect
          x="52"
          y="130"
          width="6"
          height="6"
          rx="2"
          fill="var(--main-color-bold)"
        />
        <rect
          x="78"
          y="130"
          width="6"
          height="6"
          rx="2"
          fill="var(--main-color-bold)"
        />
        <rect
          x="104"
          y="130"
          width="6"
          height="6"
          rx="2"
          fill="var(--main-color-bold)"
        />
        <rect
          y="156"
          width="6"
          height="6"
          rx="2"
          fill="var(--main-color-bold)"
        />
        <rect
          x="26"
          y="156"
          width="6"
          height="6"
          rx="2"
          fill="var(--main-color-bold)"
        />
        <rect
          x="52"
          y="156"
          width="6"
          height="6"
          rx="2"
          fill="var(--main-color-bold)"
        />
        <rect
          x="78"
          y="156"
          width="6"
          height="6"
          rx="2"
          fill="var(--main-color-bold)"
        />
        <rect
          x="104"
          y="156"
          width="6"
          height="6"
          rx="2"
          fill="var(--main-color-bold)"
        />
      </svg>
    </div>
  );
};

export { Dots };
